player-db:
  host: postgres-player-service
  port: 5432
  database: player_db
  username: tree
  password: tree

ranking-db:
  host: postgres-ranking-service
  port: 5433
  database: ranking_db
  username: tree
  password: tree

spring:
  config:
    import: "classpath:application-secret.yml"

  r2dbc:
    pool:
      enabled: false

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    root: INFO
    com.example.myapp: DEBUG
