player-db:
  host: localhost
  port: 5432
  database: player_db
  username: name
  password: pw

ranking-db:
  host: localhost
  port: 5432
  database: ranking_db
  username: name
  password: pw

spring:
  r2dbc:
    pool:
      enabled: false

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
