player-db:
  host: localhost
  port: 5432
  database: player_db
  username: username
  password: password

ranking-db:
  host: localhost
  port: 5432
  database: ranking_db
  username: username
  password: password

spring:
  r2dbc:
    pool:
      enabled: false
  jwt:
    secret: "secret"

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
